/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "index.h"
#include<stdio.h>
#define FILENAME "program.txt"
char **
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static char * result = "himanshu";
	FILE *fp;
	char ch;
	int linesCount=0;
	
	//open file in read more
	fp=fopen(FILENAME,"r");
	if(fp==NULL)
	{
		printf("File \"%s\" does not exist!!!\n",FILENAME);
		 result= "This file does not exist";
		return &result;
	}

	//read character by character and check for new line	
	while((ch=fgetc(fp))!=EOF)
	{
		if(ch=='\n')
			linesCount++;
	}
	
	//close the file
	fclose(fp);
	
	//print number of lines


	int start = argp->a;
	int end = argp->b;
	if(linesCount < start &&	 linesCount <end){
	printf("out of bound line no");
		 result= "This line does not exist";
		return &result;
        }
	
	if(start > end)
	{
	
	static char * output = "Error starting index can't be larger than  ending index";
	return &output;
	}
	//reading the data
	    char c;
	    FILE *fptr;
	    static char *ptr;
	    int count=0;
	    size_t n = 0;

	    if ((fptr = fopen("program.txt", "r")) == NULL)
	    {
		printf("Error! opening file");
		// Program exits if file pointer returns NULL.
		exit(1);         
	    }
	    fseek(fptr, 0L, SEEK_END);
	    int sz = ftell(fptr);
	    printf("%d",sz);
	    ptr = (char*)malloc(sz*sizeof(char));
	    rewind(fptr);
		while ((c = fgetc(fptr)) != EOF) {
		if(c=='\n')
		++count;
		if(count >=start -1 && count <=end -1)
		ptr[n++] = (char)c;
	    }
		ptr[n] = '\0';
	    fclose(fptr);
    
	return &ptr;
}
